services:
  - type: web
    name: driveloc
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_URL
        sync: false
      - key: APP_ENV
        value: production
      - key: AUTO_INSTALL_DB
        value: "true"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
